const IMG = id => `assets/thumbs/${id}.jpg`;
const MASTER_RAW = [
 ['p-life-forever','publication','書籍','いつまでも幸せに暮らせます','いつ幸',true],['p-life-study','publication','書籍','いつまでも幸せに暮らせます ― 聖書を学んでみませんか','聖書を学んでみませんか',true],['p-listen','publication','書籍','神さまの言われることを聞いていつまでも生き続けてください','神さまの言葉',false],['p-peace','publication','冊子','安らぎと幸せへの道','安らぎ',true],['p-origin','publication','冊子','生命 どこから？','生命どこから',false],['p-origin5','publication','冊子','生命の起源 5つの大切な質問','生命の起源',false],['p-young','publication','冊子','若い人が知りたい10の質問 役立つ答え','若い人',false],['p-bible-first','publication','冊子','初めて聖書を読む方へ','初めて聖書',false],['p-family-book','publication','冊子','あなたの家族も幸せになれます','家族冊子',true],['p-who','publication','冊子','今の時代にだれがエホバのご意志を行なっていますか','どんな人',false],['p-convention','publication','招待状','2026 地区大会招待状','地区大会',true],['p-meeting-invite','publication','招待状','会衆の集会の招待状','集会招待状',true],['p-kingdom-heard','publication','トラクト','神の王国について聞いたことがありますか','王国',true],['p-question','publication','トラクト','知りたいことがあったらどうする？','知りたい',false],['p-bible-image','publication','トラクト','聖書ってどんなイメージ？','聖書イメージ',true],['p-future','publication','トラクト','世の中はこれからどうなる？','世の中',true],['p-family','publication','トラクト','家族に大切なのは？','家族',true],['p-problems','publication','トラクト','世界に問題が多いのはどうして？','問題',false],['p-suffering-end','publication','トラクト','つらいことはいつかなくなる？','つらいこと',true],['p-dead-meet','publication','トラクト','亡くなった人にまた会えたらと思いますか','また会える',true],['p-live-forever','publication','トラクト','いつまでも生きられるようになる？','生きられる',true],['p-happy-family','publication','トラクト','ずっと幸せな家族でいるには？','幸せ家族',true],['p-help-god','publication','トラクト','助けてくれる神はいる？','助けてくれる神',true],['p-prayer','publication','トラクト','誰かが祈りを聞いてくれている？','祈り',true],['p-jesus','publication','トラクト','人生にプラスになるイエスの言葉','イエスの言葉',true],['p-kingdom-fix','publication','トラクト','神の王国は全ての問題を解決してくれる','王国が解決',true],['p-religion','publication','トラクト','どの宗教を信じるかは重要？','宗教',false],['p-g-awake-2025','publication','雑誌','目ざめよ！ 2025 No.1 物価の高騰','目ざめよ',false],['p-w-watch-2026','publication','雑誌','ものみの塔 2026 No.1 世界平和','ものみの塔',false],
 ['v-origin','video','出版物紹介','「生命 どこから？」の紹介','生命動画',true],['v-conv','video','招待動画','大会にぜひおいでください','大会動画',true],['v-help-god','video','神について','助けてくれる神はいる？','助ける神',true],['v-family','video','家族','ずっと幸せな家族でいるには？','幸せ家族',true],['v-sad-end','video','人生・将来','つらいことや悲しいこと いつかなくなる？','悲しみ',true],['v-kingdom-hall','video','組織紹介','王国会館においでください','王国会館',true],['v-who','video','組織紹介','エホバの証人 どんな人たちですか','証人とは',false],['v-study-enjoy','video','聖書・学び','聖書レッスンを楽しんでください！','レッスン',true],['v-dead-loved','video','神について','大切な人を亡くしても','亡くしても',true],['v-death-end','video','神について','死んだらそれで終わりですか','死',false],['v-family-intro','video','家族','「あなたの家族も幸せになれます」の紹介','家族紹介',false],['v-good-news','video','神について','良い知らせを聞きたいと思いませんか','良い知らせ',false],['v-2026conv','video','招待動画','2026年 エホバの証人の「永遠の幸せ」大会にお越しください','2026大会',true],['v-jesus-death','video','招待動画','イエスの死を思い起こしましょう','記念式',false],['v-why-study','video','聖書・学び','聖書を学ぶとよいのはどうして？','聖書学ぶ',true],['v-why-study-full','video','聖書・学び','聖書を学ぶとよいのはどうして？（フルバージョン）','フル版',false],['v-lesson-info','video','聖書・学び','聖書レッスンのご案内','案内',true],
 ['w-friends','video','ホワイトボード','本当の友達とは？','友達',true,'whiteboard'],['w-bully','video','ホワイトボード','いじめっ子を殴らずに撃退する','いじめ',false,'whiteboard'],['w-parent','video','ホワイトボード','親と上手に話すには？','親と話す',false,'whiteboard'],['w-devices','video','ホワイトボード','電子機器 使っている？使われている？','電子機器',true,'whiteboard'],['w-freedom','video','ホワイトボード','もっと自由がほしいなら','自由',false,'whiteboard'],['w-gossip','video','ホワイトボード','うわさ話をやめるには？','うわさ',false,'whiteboard'],['w-love','video','ホワイトボード','愛？それとも恋？','愛恋',false,'whiteboard'],['w-pressure','video','ホワイトボード','仲間の圧力に負けないために','圧力',true,'whiteboard'],['w-sns','video','ホワイトボード','SNSをスマートに','SNS',true,'whiteboard'],['w-info','video','ホワイトボード','間違った情報に気を付けて！','情報',true,'whiteboard'],['w-money','video','ホワイトボード','お金を上手に使おう','お金',false,'whiteboard'],['w-smoking','video','ホワイトボード','煙と一緒に消えないで！','煙草',false,'whiteboard'],['w-game','video','ホワイトボード','ゲーム あなたは本当の勇者？','ゲーム',false,'whiteboard'],['w-tears','video','ホワイトボード','涙から，笑顔へ','涙',false,'whiteboard'],['w-lonely','video','ホワイトボード','寂しいと感じる時どうしたらいい？','寂しい',false,'whiteboard'],['w-school','video','ホワイトボード','なんで学校に行かなきゃいけないの？','学校',false,'whiteboard'],['w-honest','video','ホワイトボード','なぜ正直って大切？','正直',false,'whiteboard'],['w-prejudice','video','ホワイトボード','偏見 もしかして私も？','偏見',false,'whiteboard']
];
const MASTER = MASTER_RAW.map(a=>({id:a[0],kind:a[1],category:a[2],title:a[3],short:a[4],favorite:a[5],style:a[6]||'',image:IMG(a[0])}));
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const uid=()=> (crypto.randomUUID ? crypto.randomUUID() : 'id-'+Date.now()+'-'+Math.random().toString(16).slice(2));
const safe = (s='') => String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state = JSON.parse(localStorage.getItem('ministryHubV3') || localStorage.getItem('serviceApp') || '{}');
state.records ||= []; state.favorites ||= Object.fromEntries(MASTER.filter(x=>x.favorite).map(x=>[x.id,true])); state.recent ||= []; state.baseline ||= {};
let minutes=30, selected={publication:{},video:{}}, pickerKind='publication', pickerFilter='favorite', libFilter='favorite';
function persist(){localStorage.setItem('ministryHubV3',JSON.stringify(state));}
function save(){persist(); renderAll();}
function fmt(m){m=+m||0; return `${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`}
function item(id){return MASTER.find(x=>x.id===id) || {id,title:id,short:id,kind:'publication',category:'その他',image:''}}
function thumbHtml(it, cls=''){let c=it.style==='whiteboard'?'whiteboard':it.category==='招待状'?'invite':it.kind==='video'?'video':''; return `<div class="thumb ${c} ${cls}"><img src="${safe(it.image)}" alt="" onerror="this.remove();this.parentElement.innerHTML='<span>${safe(it.short)}</span>'"></div>`}
function card(it, action='pick'){return `<div class="item" data-id="${it.id}" data-action="${action}">${thumbHtml(it)}<button type="button" class="star" data-star="${it.id}">${state.favorites[it.id]?'★':'☆'}</button><div class="item-title">${safe(it.title)}</div><small>${safe(it.category)}</small></div>`}
function listFor(kind,filter){let arr=MASTER.filter(x=>x.kind===kind); if(filter==='favorite') arr=arr.filter(x=>state.favorites[x.id]); if(filter==='recent') arr=state.recent.map(id=>item(id)).filter(x=>x.kind===kind); return arr;}
function renderSelected(kind){let box=$(kind==='publication'?'#selectedPubs':'#selectedVideos'); if(!box) return; let entries=Object.entries(selected[kind]); box.innerHTML=entries.map(([id,c])=>{let it=item(id);return `<div class="selected-row">${thumbHtml(it,'mini')}<div>${safe(it.title)}</div><div class="qty"><button type="button" data-dec="${id}">−</button><strong>${c}</strong><button type="button" data-inc="${id}">＋</button></div></div>`}).join('')||'<p class="muted">未選択</p>';}
function renderPicker(){let grid=$('#pickerGrid'); if(!grid) return; let q=($('#pickerSearch')?.value||'').toLowerCase(); let arr=listFor(pickerKind,pickerFilter).filter(x=>x.title.toLowerCase().includes(q)||x.category.includes(q)||x.short.includes(q)); grid.innerHTML=arr.map(x=>card(x,'pick')).join('')||'<p>該当なし</p>';}
function renderLibrary(){let grid=$('#libraryGrid'); if(!grid) return; let arr=[...listFor('publication',libFilter),...listFor('video',libFilter)]; grid.innerHTML=arr.map(x=>card(x,'none')).join('')||'<p>まだありません</p>';}
function recordTitle(r){return `${r.date||''}　${r.territory||''}${r.block?'-'+r.block:''}　${r.activityType||''}　${fmt(r.minutes)}`}
function renderHistory(){let box=$('#historyList'); if(!box) return; let q=($('#historySearch')?.value||'').toLowerCase(); let arr=[...state.records].sort((a,b)=>(b.date||'').localeCompare(a.date||'')); if(q) arr=arr.filter(r=>JSON.stringify(r).toLowerCase().includes(q)); box.innerHTML=arr.map(r=>`<div class="hist-card"><div><b>${safe(recordTitle(r))}</b><br><span>${safe([r.contactName,r.building,r.address].filter(Boolean).join(' / '))}</span><br><small>${safe(r.memo||'')}</small></div><div class="hist-actions"><button type="button" data-edit-record="${r.id}">編集</button><button type="button" data-delete-record="${r.id}" class="danger">削除</button></div></div>`).join('')||'<p>記録はまだありません。</p>';}
function renderStats(){let box=$('#statsContent'); if(!box) return; let service=0, extra=0, pubs={}, vids={}, territory={}, rv=0, studies=0; state.records.forEach(r=>{if(r.extra){extra+=(+r.minutes||0)}else{service+=(+r.minutes||0)}; Object.entries(r.publications||{}).forEach(([id,c])=>pubs[id]=(pubs[id]||0)+(+c||0)); Object.entries(r.videos||{}).forEach(([id,c])=>vids[id]=(vids[id]||0)+(+c||0)); if(r.territory){let key=`${r.territory}${r.block?'-'+r.block:''}`; territory[key]=(territory[key]||0)+1;}});
 let syStart=baselineStart(), yService=baselineService(), yExtra=baselineExtra(), yRv=+state.baseline.returnVisits||0, yStudies=+state.baseline.studies||0;
 recordsSince(syStart).forEach(r=>{ if(r.extra){yExtra+=(+r.minutes||0)}else{yService+=(+r.minutes||0)}; yRv += (+r.returnVisits||0); yStudies += (+r.studies||0); });
 const rows=obj=>Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,15).map(([id,c])=>`<tr><td>${safe(item(id).title)}</td><td>${c}</td></tr>`).join('')||'<tr><td>まだ記録なし</td><td></td></tr>';
 box.innerHTML=`<h3>今奉仕年度（${safe(syStart)}〜）</h3><table class="stats-table"><tr><th>通常奉仕</th><td>${fmt(yService)}</td></tr><tr><th>付加的奉仕</th><td>${fmt(yExtra)}</td></tr><tr><th>合計</th><td>${fmt(yService+yExtra)}</td></tr><tr><th>再訪問件数</th><td>${yRv}</td></tr><tr><th>レッスン件数</th><td>${yStudies}</td></tr></table><h3>全期間</h3><table class="stats-table"><tr><th>通常奉仕</th><td>${fmt(service)}</td></tr><tr><th>付加的奉仕</th><td>${fmt(extra)}</td></tr><tr><th>合計</th><td>${fmt(service+extra)}</td></tr></table><h3>配布物ランキング</h3><table class="stats-table">${rows(pubs)}</table><h3>動画ランキング</h3><table class="stats-table">${rows(vids)}</table><h3>区域</h3><table class="stats-table">${Object.entries(territory).map(([k,v])=>`<tr><td>${safe(k)}</td><td>${v}回</td></tr>`).join('')||'<tr><td>未記録</td><td></td></tr>'}</table>`;}
function renderDash(){let ym=new Date().toISOString().slice(0,7),s=0,e=0; state.records.filter(r=>(r.date||'').startsWith(ym)).forEach(r=>{if(r.extra){e+=(+r.minutes||0)}else{s+=(+r.minutes||0)}}); let ys=baselineService(), ye=baselineExtra(); recordsSince(baselineStart()).forEach(r=>{if(r.extra){ye+=(+r.minutes||0)}else{ys+=(+r.minutes||0)}}); $('#monthService').textContent=fmt(s); $('#monthExtra').textContent=fmt(e); $('#monthTotal').textContent=fmt(s+e); $('#rvCount').textContent=state.records.filter(r=>r.returnVisitPoint).length; if($('#yearService')) $('#yearService').textContent=fmt(ys); if($('#yearTotal')) $('#yearTotal').textContent=fmt(ys+ye);}
function filteredMapPoints(){let t=($('#mapTerritory')?.value||'').trim(), b=$('#mapBlock')?.value||'', st=$('#mapStatus')?.value||''; return state.records.filter(r=>r.returnVisitPoint&&r.lat&&r.lng).filter(r=>(!t||r.territory===t.padStart(3,'0'))&&(!b||r.block===b)&&(!st||r.rvStatus===st));}
function markerIcon(status){let color={関心あり:'#2563eb',再訪問予定:'#f97316',レッスン中:'#16a34a',保留:'#6b7280',終了:'#111827'}[status]||'#2563eb'; return L.divIcon({className:'custom-pin',html:`<span style="background:${color}"></span>`,iconSize:[24,24],iconAnchor:[12,24]});}
function renderMap(){let list=$('#rvList'); if(!list) return; let pts=filteredMapPoints(); list.innerHTML=pts.map(r=>`<div class="rv-card"><b>${safe(r.contactName||r.rvStatus||'再訪問')}</b> <span>${safe(r.territory||'')}${r.block?'-'+safe(r.block):''}</span><br>${safe(r.address||'')}<br>${r.nextDate?`次回: ${safe(r.nextDate)}<br>`:''}<a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${r.lat},${r.lng}">Google Mapで開く</a></div>`).join('')||'<p>再訪問地点はまだありません。記録画面で「現在地から住所入力」→「再訪問地点に登録」にチェックして保存してください。</p>';
 const canvas=$('#mapCanvas'); if(!canvas) return; setTimeout(()=>{ if(!window.L){canvas.innerHTML='<p class="muted">地図ライブラリを読み込めませんでした。通信環境を確認してください。</p>';return;} if(window.mapObj){window.mapObj.remove(); window.mapObj=null;} let center=pts[0]?[pts[0].lat,pts[0].lng]:[34.7108,137.7261]; window.mapObj=L.map('mapCanvas').setView(center, pts[0]?14:11); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(window.mapObj); pts.forEach(r=>L.marker([r.lat,r.lng],{icon:markerIcon(r.rvStatus)}).addTo(window.mapObj).bindPopup(`<b>${safe(r.contactName||r.rvStatus||'再訪問')}</b><br>${safe(r.territory||'')}${r.block?'-'+safe(r.block):''}<br>${safe(r.address||'')}<br>${safe(r.memo||'')}`)); setTimeout(()=>window.mapObj.invalidateSize(),100); },80);}
function renderAll(){renderDash();renderLibrary();renderHistory();renderStats(); if($('#map')?.classList.contains('active')) renderMap();}
function clearForm(){selected={publication:{},video:{}}; $('#recordForm').reset(); $('#date').value=new Date().toISOString().slice(0,10); minutes=30; $('#timeDisplay').textContent=fmt(minutes); $('#editingId').value=''; $('#formTitle').textContent='今日の記録'; $('#saveBtn').textContent='保存'; $('#cancelEditBtn').hidden=true; renderSelected('publication'); renderSelected('video');}
function fillForm(r){$('#editingId').value=r.id; $('#date').value=r.date||''; $('#activityType').value=r.activityType||'戸別'; $('#territory').value=r.territory||''; $('#block').value=r.block||''; minutes=+r.minutes||0; $('#timeDisplay').textContent=fmt(minutes); $('#contactName').value=r.contactName||''; $('#building').value=r.building||''; $('#address').value=r.address||''; $('#lat').value=r.lat||''; $('#lng').value=r.lng||''; $('#rvStatus').value=r.rvStatus||'関心あり'; $('#nextDate').value=r.nextDate||''; $('#saveReturnVisit').checked=!!r.returnVisitPoint; $$('input[name="topic"]').forEach(x=>x.checked=(r.topics||[]).includes(x.value)); selected={publication:{...(r.publications||{})}, video:{...(r.videos||{})}}; $('#returnVisits').value=r.returnVisits||0; $('#studies').value=r.studies||0; $('#memo').value=r.memo||''; $('#formTitle').textContent='記録を編集'; $('#saveBtn').textContent='更新'; $('#cancelEditBtn').hidden=false; renderSelected('publication'); renderSelected('video'); document.querySelector('[data-view="record"]').click(); window.scrollTo({top:0,behavior:'smooth'});}
function renderBaselineForm(){ if(!$('#baselineStart')) return; $('#baselineStart').value=baselineStart(); $('#baselineServiceHours').value=Math.floor(baselineService()/60); $('#baselineServiceMinutes').value=baselineService()%60; $('#baselineExtraHours').value=Math.floor(baselineExtra()/60); $('#baselineExtraMinutes').value=baselineExtra()%60; $('#baselineReturnVisits').value=+state.baseline.returnVisits||0; $('#baselineStudies').value=+state.baseline.studies||0; $('#baselineNote').value=state.baseline.note||'';}
function saveBaselineFromForm(){ let sm=(+$('#baselineServiceHours').value||0)*60+(+$('#baselineServiceMinutes').value||0); let em=(+$('#baselineExtraHours').value||0)*60+(+$('#baselineExtraMinutes').value||0); state.baseline={startDate:$('#baselineStart').value||currentServiceYearStart(), serviceMinutes:sm, extraMinutes:em, returnVisits:+$('#baselineReturnVisits').value||0, studies:+$('#baselineStudies').value||0, note:$('#baselineNote').value||''}; persist(); renderAll(); alert('今奉仕年度の初期累計を保存しました');}
function init(){ $('#date').value=new Date().toISOString().slice(0,10); $('#timeDisplay').textContent=fmt(minutes); renderBaselineForm(); if($('#saveBaselineBtn')) $('#saveBaselineBtn').onclick=saveBaselineFromForm; $('#plus10').onclick=()=>{minutes+=10; $('#timeDisplay').textContent=fmt(minutes)}; $('#minus10').onclick=()=>{minutes=Math.max(0,minutes-10); $('#timeDisplay').textContent=fmt(minutes)};
 $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active'); renderAll();});
 $$('[data-open-picker]').forEach(b=>b.onclick=()=>{pickerKind=b.dataset.openPicker; $('#pickerTitle').textContent=pickerKind==='publication'?'配布物を追加':'動画を追加'; $('#pickerSearch').value=''; $('#picker').showModal(); renderPicker();});
 $('#closePicker').onclick=()=>$('#picker').close(); $('#pickerSearch').oninput=renderPicker; $('#historySearch').oninput=renderHistory; ['#mapTerritory','#mapBlock','#mapStatus'].forEach(s=>$(s).oninput=renderMap);
 $$('.picker-tab').forEach(b=>b.onclick=()=>{$$('.picker-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');pickerFilter=b.dataset.filter;renderPicker();}); $$('.lib-tab').forEach(b=>b.onclick=()=>{$$('.lib-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');libFilter=b.dataset.lib;renderLibrary();});
 document.addEventListener('click',e=>{let star=e.target.closest('[data-star]'); if(star){e.stopPropagation(); let id=star.dataset.star; state.favorites[id]=!state.favorites[id]; save(); renderPicker(); return;} let el=e.target.closest('.item[data-id]'); if(el && el.dataset.action==='pick'){let id=el.dataset.id; selected[pickerKind][id]=(selected[pickerKind][id]||0)+1; state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,30); persist(); renderSelected(pickerKind); renderPicker(); renderLibrary();} let inc=e.target.closest('[data-inc]'); if(inc){let id=inc.dataset.inc; let k=item(id).kind; selected[k][id]++; renderSelected(k);} let dec=e.target.closest('[data-dec]'); if(dec){let id=dec.dataset.dec; let k=item(id).kind; selected[k][id]--; if(selected[k][id]<=0) delete selected[k][id]; renderSelected(k);} let ed=e.target.closest('[data-edit-record]'); if(ed){let r=state.records.find(x=>x.id===ed.dataset.editRecord); if(r) fillForm(r);} let del=e.target.closest('[data-delete-record]'); if(del){if(confirm('この記録を削除しますか？')){state.records=state.records.filter(x=>x.id!==del.dataset.deleteRecord); save();}}});
 $('#locateBtn').onclick=()=>{ if(!navigator.geolocation){alert('位置情報が使えません');return;} $('#locateBtn').textContent='取得中…'; navigator.geolocation.getCurrentPosition(async pos=>{let {latitude,longitude}=pos.coords; $('#lat').value=latitude; $('#lng').value=longitude; try{let res=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}&accept-language=ja`); let j=await res.json(); $('#address').value=j.display_name||`${latitude},${longitude}`;}catch{ $('#address').value=`${latitude},${longitude}`;} $('#locateBtn').textContent='📍 現在地から住所入力';},err=>{alert('位置情報を取得できませんでした。Safari/Chromeで位置情報の許可を確認してください。'); $('#locateBtn').textContent='📍 現在地から住所入力';},{enableHighAccuracy:true,timeout:10000});};
 $('#openMapBtn').onclick=()=>{let q=$('#lat').value&&$('#lng').value?`${$('#lat').value},${$('#lng').value}`:encodeURIComponent($('#address').value); if(q) window.open(`https://www.google.com/maps/search/?api=1&query=${q}`,'_blank');};
 $('#recordForm').onsubmit=e=>{e.preventDefault(); let opt=$('#activityType').selectedOptions[0]; let rec={id:$('#editingId').value||uid(),date:$('#date').value,activityType:$('#activityType').value,extra:!!opt.dataset.extra,territory:$('#territory').value?$('#territory').value.padStart(3,'0'):'',block:$('#block').value,minutes,contactName:$('#contactName').value,building:$('#building').value,address:$('#address').value,lat:parseFloat($('#lat').value)||null,lng:parseFloat($('#lng').value)||null,returnVisitPoint:$('#saveReturnVisit').checked,rvStatus:$('#rvStatus').value,nextDate:$('#nextDate').value,topics:$$('input[name="topic"]:checked').map(x=>x.value),publications:{...selected.publication},videos:{...selected.video},returnVisits:+$('#returnVisits').value||0,studies:+$('#studies').value||0,memo:$('#memo').value}; let i=state.records.findIndex(x=>x.id===rec.id); if(i>=0) state.records[i]=rec; else state.records.push(rec); persist(); clearForm(); renderAll(); alert(i>=0?'更新しました':'保存しました');};
 $('#cancelEditBtn').onclick=clearForm; $('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); let a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='service-record-backup.json'; a.click();};
 $('#exportCsvBtn').onclick=()=>{let head=['日付','区分','時間','付加的','区域','ブロック','名前','住宅名','住所','ステータス','次回予定','再訪問','レッスン','メモ']; let rows=state.records.map(r=>[r.date,r.activityType,fmt(r.minutes),r.extra?'1':'0',r.territory,r.block,r.contactName,r.building,r.address,r.rvStatus,r.nextDate,r.returnVisits,r.studies,r.memo].map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')); let blob=new Blob(['\ufeff'+head.join(',')+'\n'+rows.join('\n')],{type:'text/csv'}); let a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='service-record.csv'; a.click();};
 renderSelected('publication'); renderSelected('video'); renderAll(); }
document.addEventListener('DOMContentLoaded', init);
