'use strict';
if ('serviceWorker' in navigator) navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});
const FIREBASE_CONFIG={apiKey:'AIzaSyBzxU5UV87QyxvvpaUVW9KSqYTzguJwGOQ',authDomain:'ministry-hub-app-da2c7.firebaseapp.com',projectId:'ministry-hub-app-da2c7',storageBucket:'ministry-hub-app-da2c7.firebasestorage.app',messagingSenderId:'975594347445',appId:'1:975594347445:web:3b1354103e41a41ac817fc'};
const STORE_KEY='ministryHubPeopleV17';
const OLD_KEYS=['ministryHubV16','ミニストリーHubV16','ministryHubV3','serviceApp'];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function parseTime(v){ if(typeof v==='number') return Math.max(0,Math.round(v)); let s=String(v||'').trim(); if(!s)return 0; s=s.replace('：',':'); if(s.includes(':')){let [h,m]=s.split(':').map(x=>parseInt(x,10)||0); return Math.max(0,h*60+m)} return Math.max(0,parseInt(s,10)||0); }
function fmt(min){min=Math.max(0,Math.round(+min||0)); return Math.floor(min/60)+':'+String(min%60).padStart(2,'0')}
function serviceYearStart(){const d=new Date(); const y=d.getMonth()>=8?d.getFullYear():d.getFullYear()-1; return `${y}-09-01`;}
const blankState=()=>({version:17,records:[],people:[],baseline:{start:serviceYearStart(),normalMinutes:0,extraMinutes:0,note:''},recent:[],favorites:{},updatedAt:Date.now()});
let state=loadState();
let editingRecordId=null, currentNormal=0, currentExtra=0, currentLat=null, currentLng=null, map=null, markers=[];
function normalizeState(s){s=s||{}; s.records=Array.isArray(s.records)?s.records:[]; s.people=Array.isArray(s.people)?s.people:[]; s.baseline=s.baseline||{start:serviceYearStart(),normalMinutes:0,extraMinutes:0,note:''}; s.baseline.normalMinutes=parseTime(s.baseline.normalMinutes??s.baseline.serviceMinutes); s.baseline.extraMinutes=parseTime(s.baseline.extraMinutes); s.baseline.start=s.baseline.start||serviceYearStart(); s.records=s.records.map(normalizeRecord).filter(Boolean); s.people=s.people.map(normalizePerson).filter(Boolean); ensurePeopleFromRecords(s); return s; }
function normalizeRecord(r){ if(!r)return null; const activity=r.activityType||r.activity||'戸別'; const isExtra=r.extra===true||/大会|メンテ|付加/.test(activity); const normalMinutes=parseTime(r.normalMinutes ?? (isExtra?0:r.minutes)); const extraMinutes=parseTime(r.extraMinutes ?? (isExtra?r.minutes:0)); return {id:r.id||uid(),date:r.date||today(),activityType:activity,normalMinutes,extraMinutes,personId:r.personId||'',personName:r.personName||r.contactName||r.name||'',gender:r.gender||'',ageGroup:r.ageGroup||'',territory:r.territory||'',block:r.block||'なし',building:r.building||'',address:r.address||'',lat:r.lat??r.latitude??null,lng:r.lng??r.longitude??null,rvStatus:r.rvStatus||'未分類',nextDate:r.nextDate||'',topics:Array.isArray(r.topics)?r.topics:[],lessonStatus:r.lessonStatus||'なし',lessonMaterial:r.lessonMaterial||'',lessonNo:r.lessonNo||'',memo:r.memo||'',createdAt:r.createdAt||Date.now(),updatedAt:r.updatedAt||Date.now()}; }
function normalizePerson(p){ if(!p)return null; return {id:p.id||uid(),name:p.name||p.personName||p.contactName||'名前未入力',gender:p.gender||'',ageGroup:p.ageGroup||'',territory:p.territory||'',block:p.block||'なし',building:p.building||'',address:p.address||'',lat:p.lat??null,lng:p.lng??null,rvStatus:p.rvStatus||'関心あり',nextDate:p.nextDate||'',topics:Array.isArray(p.topics)?p.topics:[],lessonStatus:p.lessonStatus||'なし',lessonMaterial:p.lessonMaterial||'',lessonNo:p.lessonNo||'',memo:p.memo||'',createdAt:p.createdAt||Date.now(),updatedAt:p.updatedAt||Date.now()}; }
function ensurePeopleFromRecords(s){const byKey=new Map(s.people.map(p=>[personKey(p),p])); for(const r of s.records){ if(!r.personName && !r.address) continue; let key=personKey({name:r.personName,address:r.address,building:r.building}); let p=byKey.get(key); if(!p){p=normalizePerson({...r,name:r.personName}); s.people.push(p); byKey.set(key,p);} r.personId=r.personId||p.id; }}
function personKey(p){return [p.name||'',p.address||'',p.building||''].join('|').trim();}
function loadState(){let raw=localStorage.getItem(STORE_KEY); if(raw){try{return normalizeState(JSON.parse(raw))}catch{}} for(const k of OLD_KEYS){raw=localStorage.getItem(k); if(raw){try{const migrated=migrateOld(JSON.parse(raw)); saveLocal(migrated); return migrated;}catch(e){console.warn(e)}}} return blankState();}
function migrateOld(old){let s=blankState(); if(old.baseline){s.baseline={start:old.baseline.start||serviceYearStart(),normalMinutes:parseTime(old.baseline.normalMinutes??old.baseline.serviceMinutes),extraMinutes:parseTime(old.baseline.extraMinutes),note:old.baseline.note||'移行データ'};} s.records=(old.records||[]).map(normalizeRecord).filter(Boolean); if(old.people) s.people=old.people.map(normalizePerson).filter(Boolean); ensurePeopleFromRecords(s); return normalizeState(s);}
function saveLocal(s=state){s.updatedAt=Date.now(); localStorage.setItem(STORE_KEY,JSON.stringify(s));}
function setTab(name){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name)); $$('.panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+name)); if(name==='map') setTimeout(renderMap,100);}
function setTimes(n,e){currentNormal=Math.max(0,n||0);currentExtra=Math.max(0,e||0);$('#normalTimeText').textContent=fmt(currentNormal);$('#extraTimeText').textContent=fmt(currentExtra)}
function topicsFromForm(){return $$('.topic:checked').map(x=>x.value)}
function setTopics(vals=[]){$$('.topic').forEach(x=>x.checked=vals.includes(x.value))}
function recordFromForm(){const pId=$('#personSelect').value; return normalizeRecord({id:editingRecordId||uid(),date:$('#recDate').value||today(),activityType:$('#activityType').value,normalMinutes:currentNormal,extraMinutes:currentExtra,personId:pId,personName:$('#personName').value.trim(),gender:$('#gender').value,ageGroup:$('#ageGroup').value,territory:$('#territory').value.trim(),block:$('#block').value,building:$('#building').value.trim(),address:$('#address').value.trim(),lat:currentLat,lng:currentLng,rvStatus:$('#rvStatus').value,nextDate:$('#nextDate').value,topics:topicsFromForm(),lessonStatus:$('#lessonStatus').value,lessonMaterial:$('#lessonMaterial').value.trim(),lessonNo:$('#lessonNo').value.trim(),memo:$('#memo').value.trim(),createdAt:editingRecordId?(state.records.find(r=>r.id===editingRecordId)?.createdAt||Date.now()):Date.now(),updatedAt:Date.now()});}
function upsertPersonFromRecord(r){if(!$('#saveToPerson').checked) return r.personId; if(!r.personName && !r.address) return r.personId||''; let p= r.personId ? state.people.find(x=>x.id===r.personId) : null; if(!p){const key=personKey({name:r.personName,address:r.address,building:r.building}); p=state.people.find(x=>personKey(x)===key);} if(!p){p=normalizePerson({id:uid(),name:r.personName||'名前未入力'}); state.people.push(p);} Object.assign(p,{name:r.personName||p.name,gender:r.gender||p.gender,ageGroup:r.ageGroup||p.ageGroup,territory:r.territory,block:r.block,building:r.building,address:r.address,lat:r.lat??p.lat,lng:r.lng??p.lng,rvStatus:r.rvStatus,nextDate:r.nextDate,topics:r.topics,lessonStatus:r.lessonStatus,lessonMaterial:r.lessonMaterial,lessonNo:r.lessonNo,memo:r.memo||p.memo,updatedAt:Date.now()}); return p.id;}
function fillFormFromRecord(r){editingRecordId=r.id; $('#recDate').value=r.date; $('#activityType').value=r.activityType; setTimes(r.normalMinutes,r.extraMinutes); $('#personSelect').value=r.personId||''; $('#personName').value=r.personName||''; $('#gender').value=r.gender||''; $('#ageGroup').value=r.ageGroup||''; $('#territory').value=r.territory||''; $('#block').value=r.block||'なし'; $('#building').value=r.building||''; $('#address').value=r.address||''; currentLat=r.lat; currentLng=r.lng; $('#rvStatus').value=r.rvStatus||'未分類'; $('#nextDate').value=r.nextDate||''; setTopics(r.topics||[]); $('#lessonStatus').value=r.lessonStatus||'なし'; $('#lessonMaterial').value=r.lessonMaterial||''; $('#lessonNo').value=r.lessonNo||''; $('#memo').value=r.memo||''; $('#saveRecordBtn').textContent='更新する'; setTab('record'); window.scrollTo({top:0,behavior:'smooth'});}
function clearForm(){editingRecordId=null; $('#recDate').value=today(); $('#activityType').value='戸別'; setTimes(0,0); $('#personSelect').value=''; ['personName','gender','ageGroup','territory','building','address','nextDate','lessonMaterial','lessonNo','memo'].forEach(id=>{$('#'+id).value=''}); $('#block').value='なし'; $('#rvStatus').value='関心あり'; $('#lessonStatus').value='なし'; setTopics([]); currentLat=null; currentLng=null; $('#saveRecordBtn').textContent='記録を保存';}
function saveRecord(){const r=recordFromForm(); r.personId=upsertPersonFromRecord(r); const i=state.records.findIndex(x=>x.id===r.id); if(i>=0) state.records[i]=r; else state.records.push(r); saveLocal(); clearForm(); renderAll(); alert('保存しました');}
function applyPersonToForm(id){const p=state.people.find(x=>x.id===id); if(!p)return; $('#personName').value=p.name||''; $('#gender').value=p.gender||''; $('#ageGroup').value=p.ageGroup||''; $('#territory').value=p.territory||''; $('#block').value=p.block||'なし'; $('#building').value=p.building||''; $('#address').value=p.address||''; currentLat=p.lat; currentLng=p.lng; $('#rvStatus').value=p.rvStatus||'関心あり'; $('#nextDate').value=p.nextDate||''; setTopics(p.topics||[]); $('#lessonStatus').value=p.lessonStatus||'なし'; $('#lessonMaterial').value=p.lessonMaterial||''; $('#lessonNo').value=p.lessonNo||''; $('#memo').value=p.memo||'';}
function sums(){const month=today().slice(0,7), start=state.baseline.start||serviceYearStart(); let mn=0,me=0,yn=state.baseline.normalMinutes||0,ye=state.baseline.extraMinutes||0; for(const r of state.records){if((r.date||'').slice(0,7)===month){mn+=r.normalMinutes||0;me+=r.extraMinutes||0} if((r.date||'')>=start){yn+=r.normalMinutes||0;ye+=r.extraMinutes||0}} return {mn,me,yn,ye};}
function renderSummary(){const x=sums(); $('#monthNormal').textContent=fmt(x.mn); $('#monthExtra').textContent=fmt(x.me); $('#monthTotal').textContent=fmt(x.mn+x.me); $('#yearNormal').textContent=fmt(x.yn); $('#yearExtra').textContent=fmt(x.ye); $('#yearTotal').textContent=fmt(x.yn+x.ye); $('#personCount').textContent=state.people.length; $('#lessonCount').textContent=state.people.filter(p=>p.lessonStatus==='レッスン中').length;}
function renderPersonSelect(){const sel=$('#personSelect'), cur=sel.value; sel.innerHTML='<option value="">新規または未選択</option>'+state.people.slice().sort((a,b)=>(a.name||'').localeCompare(b.name||'ja')).map(p=>`<option value="${p.id}">${esc(p.name)}${p.territory?' / '+esc(p.territory):''}${p.block&&p.block!=='なし'?'-'+esc(p.block):''}</option>`).join(''); sel.value=cur;}
function renderPeople(){const q=($('#peopleSearch')?.value||'').toLowerCase(); const rows=state.people.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).sort((a,b)=>(a.nextDate||'9999').localeCompare(b.nextDate||'9999')); $('#peopleList').innerHTML=rows.length?rows.map(p=>{const count=state.records.filter(r=>r.personId===p.id).length; return `<div class="row"><div><div class="row-title">${esc(p.name)} ${p.lessonStatus==='レッスン中'?'<span class="badge">レッスン中</span>':''}</div><div class="row-meta">${esc([p.gender,p.ageGroup,p.territory,p.block].filter(Boolean).join(' / '))}\n${esc(p.address||'')} ${esc(p.building||'')}\n次回: ${esc(p.nextDate||'未定')} / 記録 ${count}件\n${esc((p.topics||[]).join('・'))}</div></div><div class="row-actions"><button data-person-record="${p.id}">記録</button><button data-person-edit="${p.id}">編集</button><button class="danger" data-person-delete="${p.id}">削除</button></div></div>`}).join(''):'<p class="muted">人物はまだありません。</p>';}
function renderHistory(){const q=($('#historySearch')?.value||'').toLowerCase(); const rows=state.records.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>(b.date||'').localeCompare(a.date||'') || (b.createdAt||0)-(a.createdAt||0)); $('#historyList').innerHTML=rows.length?rows.map(r=>`<div class="row"><div><div class="row-title">${esc(r.date)}　${esc(r.activityType)}　通常 ${fmt(r.normalMinutes)}　付加 ${fmt(r.extraMinutes)}</div><div class="row-meta">${esc(r.personName||'')} ${esc(r.gender||'')} ${esc(r.ageGroup||'')}\n${esc([r.territory,r.block,r.address,r.building].filter(Boolean).join(' / '))}\n${esc(r.memo||'')}</div></div><div class="row-actions"><button data-rec-edit="${r.id}">編集</button><button class="danger" data-rec-delete="${r.id}">削除</button></div></div>`).join(''):'<p class="muted">記録はまだありません。</p>';}
function renderStats(){const byMonth={}; for(const r of state.records){const m=(r.date||'').slice(0,7)||'未日付'; byMonth[m]??={n:0,e:0,c:0}; byMonth[m].n+=r.normalMinutes||0; byMonth[m].e+=r.extraMinutes||0; byMonth[m].c++;} $('#statsBox').innerHTML='<table class="stats-table"><tr><th>月</th><th>通常</th><th>付加</th><th>合計</th><th>件数</th></tr>'+Object.entries(byMonth).sort().reverse().map(([m,x])=>`<tr><td>${m}</td><td>${fmt(x.n)}</td><td>${fmt(x.e)}</td><td>${fmt(x.n+x.e)}</td><td>${x.c}</td></tr>`).join('')+'</table>';}
function loadBaselineForm(){ $('#baselineStart').value=state.baseline.start||serviceYearStart(); $('#baselineNormal').value=fmt(state.baseline.normalMinutes||0); $('#baselineExtra').value=fmt(state.baseline.extraMinutes||0); $('#baselineNote').value=state.baseline.note||'';}
function saveBaseline(){state.baseline={start:$('#baselineStart').value||serviceYearStart(),normalMinutes:parseTime($('#baselineNormal').value),extraMinutes:parseTime($('#baselineExtra').value),note:$('#baselineNote').value}; saveLocal(); renderAll(); alert('初期累計を保存しました');}
async function geocodeAddress(){const addr=$('#address').value.trim(); if(!addr){alert('住所を入力してください'); return;} try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(addr)); const arr=await res.json(); if(!arr.length){alert('見つかりませんでした。現在地取得か地図で確認してください。'); return;} currentLat=+arr[0].lat; currentLng=+arr[0].lon; alert('ピン位置を取得しました');}catch(e){alert('住所検索に失敗しました: '+e.message)}}
function useCurrentLocation(){if(!navigator.geolocation){alert('位置情報が使えません');return;} navigator.geolocation.getCurrentPosition(pos=>{currentLat=pos.coords.latitude; currentLng=pos.coords.longitude; alert('現在地を取得しました');},err=>alert('取得できません: '+err.message),{enableHighAccuracy:true,timeout:10000});}
function openGoogleMap(){const addr=$('#address').value.trim(); if(currentLat&&currentLng) window.open(`https://www.google.com/maps/search/?api=1&query=${currentLat},${currentLng}`,'_blank'); else if(addr) window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(addr),'_blank'); else alert('住所か位置情報が必要です');}
function renderMap(){if(!window.L)return; if(!map){map=L.map('map').setView([34.7108,137.7261],12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);} markers.forEach(m=>m.remove()); markers=[]; const pts=state.people.filter(p=>p.lat&&p.lng); pts.forEach(p=>{const marker=L.marker([p.lat,p.lng]).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.address||'')}<br>次回: ${esc(p.nextDate||'未定')}`); markers.push(marker);}); if(pts.length){map.fitBounds(pts.map(p=>[p.lat,p.lng]),{padding:[30,30]});} setTimeout(()=>map.invalidateSize(),100);}
function renderAll(){renderSummary();renderPersonSelect();renderPeople();renderHistory();renderStats();loadBaselineForm(); if($('#tab-map').classList.contains('active')) renderMap();}
function exportJson(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='service-record-backup.json'; a.click();}
async function importJson(file){const txt=await file.text(); const incoming=normalizeState(JSON.parse(txt)); if(!confirm('バックアップを現在のデータと統合しますか？'))return; const rec=new Map(state.records.map(r=>[r.id,r])); incoming.records.forEach(r=>rec.set(r.id,r)); const ppl=new Map(state.people.map(p=>[p.id,p])); incoming.people.forEach(p=>ppl.set(p.id,p)); state=normalizeState({...state,records:[...rec.values()],people:[...ppl.values()],baseline:incoming.baseline||state.baseline}); saveLocal(); renderAll(); alert('復元しました');}
let auth=null, db=null, user=null;
function initFirebase(){try{const cfg=JSON.parse(localStorage.getItem('ministryHubFirebaseConfig')||'null')||FIREBASE_CONFIG; $('#firebaseConfigText').value=JSON.stringify(cfg,null,2); if(!firebase.apps.length) firebase.initializeApp(cfg); auth=firebase.auth(); db=firebase.firestore(); auth.onAuthStateChanged(u=>{user=u; $('#loginBtn').hidden=!!u; $('#logoutBtn').hidden=!u; setSyncStatus(u?'同期準備OK：'+(u.email||u.displayName):'未ログイン');});}catch(e){setSyncStatus('Firebase設定エラー: '+e.message)}}
function setSyncStatus(t){$('#syncStatus').textContent=t;}
async function pushCloud(){if(!user||!db){alert('先にログインしてください');return;} await db.collection('users').doc(user.uid).collection('apps').doc('ministryHubV17').set({state,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}); setSyncStatus('クラウドへ保存しました：'+(user.email||'')); alert('クラウドへ保存しました');}
async function pullCloud(){if(!user||!db){alert('先にログインしてください');return;} const snap=await db.collection('users').doc(user.uid).collection('apps').doc('ministryHubV17').get(); if(!snap.exists||!snap.data().state){alert('クラウドにデータがありません');return;} if(!confirm('クラウドのデータをこの端末に読み込みます。現在の端末データと統合しますか？'))return; const incoming=normalizeState(snap.data().state); const rec=new Map(state.records.map(r=>[r.id,r])); incoming.records.forEach(r=>rec.set(r.id,r)); const ppl=new Map(state.people.map(p=>[p.id,p])); incoming.people.forEach(p=>ppl.set(p.id,p)); state=normalizeState({...state,records:[...rec.values()],people:[...ppl.values()],baseline:incoming.baseline||state.baseline}); saveLocal(); renderAll(); alert('クラウドから読み込みました');}
function bindEvents(){ $('#tabs').addEventListener('click',e=>{if(e.target.dataset.tab)setTab(e.target.dataset.tab)}); document.body.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; if(b.dataset.minTarget){let target=b.dataset.minTarget; let val=target==='normal'?currentNormal:currentExtra; if(b.dataset.set!=null) val=parseTime(b.dataset.set); else val+=parseInt(b.dataset.delta,10)||0; if(target==='normal') setTimes(val,currentExtra); else setTimes(currentNormal,val);} if(b.dataset.recEdit) fillFormFromRecord(state.records.find(r=>r.id===b.dataset.recEdit)); if(b.dataset.recDelete&&confirm('削除しますか？')){state.records=state.records.filter(r=>r.id!==b.dataset.recDelete);saveLocal();renderAll();} if(b.dataset.personRecord){$('#personSelect').value=b.dataset.personRecord;applyPersonToForm(b.dataset.personRecord);setTab('record')} if(b.dataset.personEdit){const p=state.people.find(x=>x.id===b.dataset.personEdit); if(p){$('#personSelect').value=p.id;applyPersonToForm(p.id);setTab('record')}} if(b.dataset.personDelete&&confirm('人物を削除しますか？ 記録は残ります。')){state.people=state.people.filter(p=>p.id!==b.dataset.personDelete);saveLocal();renderAll();}});
 $('#personSelect').addEventListener('change',e=>applyPersonToForm(e.target.value)); $('#saveRecordBtn').onclick=saveRecord; $('#clearRecordBtn').onclick=clearForm; $('#useCurrentLocationBtn').onclick=useCurrentLocation; $('#geocodeBtn').onclick=geocodeAddress; $('#openGoogleMapBtn').onclick=openGoogleMap; $('#peopleSearch').oninput=renderPeople; $('#historySearch').oninput=renderHistory; $('#saveBaselineBtn').onclick=saveBaseline; $('#exportJsonBtn').onclick=exportJson; $('#importJsonBtn').onclick=()=>$('#importJsonFile').click(); $('#importJsonFile').onchange=e=>{const f=e.target.files[0]; if(f) importJson(f); e.target.value='';}; $('#loginBtn').onclick=()=>auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(e=>alert(e.message)); $('#logoutBtn').onclick=()=>auth.signOut(); $('#pushCloudBtn').onclick=pushCloud; $('#pullCloudBtn').onclick=pullCloud; $('#saveFirebaseConfigBtn').onclick=()=>{try{const cfg=JSON.parse($('#firebaseConfigText').value);localStorage.setItem('ministryHubFirebaseConfig',JSON.stringify(cfg));alert('保存しました。再読み込みします');location.reload();}catch(e){alert('JSONを確認してください: '+e.message)}}; }
function init(){clearForm(); bindEvents(); renderAll(); initFirebase();}
document.addEventListener('DOMContentLoaded',init);
