'use strict';
if ('serviceWorker' in navigator) navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});

const FIREBASE_CONFIG={apiKey:'AIzaSyBzxU5UV87QyxvvpaUVW9KSqYTzguJwGOQ',authDomain:'ministry-hub-app-da2c7.firebaseapp.com',projectId:'ministry-hub-app-da2c7',storageBucket:'ministry-hub-app-da2c7.firebasestorage.app',messagingSenderId:'975594347445',appId:'1:975594347445:web:3b1354103e41a41ac817fc'};
const STORE_KEY='ministryHubFinalSafeV1';
const OLD_KEYS=['ministryHubFinal','ministryHubPeopleV17','ministryHubV16','ミニストリーHubV16','ministryHubV3','serviceApp'];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function parseTime(v){ if(typeof v==='number') return Math.max(0,Math.round(v)); let s=String(v||'').trim().replace('：',':'); if(!s) return 0; if(s.includes(':')){const [h,m]=s.split(':').map(x=>parseInt(x,10)||0); return Math.max(0,h*60+m);} return Math.max(0,parseInt(s,10)||0); }
function fmt(min){ min=Math.max(0,Math.round(+min||0)); return Math.floor(min/60)+':'+String(min%60).padStart(2,'0'); }
function serviceYearStart(){const d=new Date(); const y=d.getMonth()>=8?d.getFullYear():d.getFullYear()-1; return `${y}-09-01`;}

const MEDIA=[
  ['p-life-forever','book','書籍','いつまでも幸せに暮らせます','assets/thumbs/p-life-forever.jpg'],
  ['p-life-study','book','書籍','いつまでも幸せに暮らせます — 聖書を学んでみませんか','assets/thumbs/p-life-study.jpg'],
  ['p-family-book','book','冊子','あなたの家族も幸せになれます','assets/thumbs/p-family-book.jpg'],
  ['p-convention','invitation','招待状','2026 地区大会招待状','assets/thumbs/p-convention.jpg'],
  ['p-meeting','invitation','招待状','会衆の集会の招待状','assets/thumbs/p-bible-first.jpg'],
  ['p-kingdom-heard','tract','トラクト','神の王国について聞いたことがありますか','assets/thumbs/p-kingdom-heard.jpg'],
  ['p-bible-image','tract','トラクト','聖書ってどんなイメージ？','assets/thumbs/p-bible-image.jpg'],
  ['p-future','tract','トラクト','世の中はこれからどうなる？','assets/thumbs/p-future.jpg'],
  ['p-family','tract','トラクト','家族に大切なのは？','assets/thumbs/p-family.jpg'],
  ['p-dead-meet','tract','トラクト','亡くなった人にまた会えたらと思いますか','assets/thumbs/p-dead-meet.jpg'],
  ['p-help-god','tract','トラクト','助けてくれる神はいる？','assets/thumbs/p-help-god.jpg'],
  ['p-happy-family','tract','トラクト','ずっと幸せな家族でいるには？','assets/thumbs/p-happy-family.jpg'],
  ['p-kingdom-fix','tract','トラクト','神の王国は全ての問題を解決してくれる','assets/thumbs/p-kingdom-fix.jpg'],
  ['p-listen','booklet','パンフレット','神さまの言われることを聞いていつまでも生き続けてください','assets/thumbs/p-listen.jpg'],
  ['p-jesus','booklet','パンフレット','イエスから学べること','assets/thumbs/p-jesus.jpg'],
  ['p-origin','brochure','冊子','生命の起源 5つの大切な質問','assets/thumbs/p-origin.jpg'],
  ['p-g-awake-2025','magazine','雑誌','目ざめよ！ 2025 No.1 物価の高騰 どうしたらいい？','assets/thumbs/p-g-awake-2025.jpg'],
  ['p-g-awake-2024','magazine','雑誌','目ざめよ！ 2024 No.1 どうなってしまった？思いやりの気持ち','assets/thumbs/p-g-awake-2024.jpg'],
  ['p-g-awake-2023','magazine','雑誌','目ざめよ！ 2023 No.1 地球はどうなる？','assets/thumbs/p-g-awake-2023.jpg'],
  ['p-bible-first','booklet','パンフレット','初めて聖書を読む方へ','assets/thumbs/p-bible-first.jpg'],
  ['v-life-origin','video','動画','「生命 どこから？」の紹介','assets/thumbs/v-color-a-01.jpg'],
  ['v-convention','video','動画','大会にぜひおいでください','assets/thumbs/v-color-a-02.jpg'],
  ['v-help-god','video','動画','助けてくれる神はいる？','assets/thumbs/v-color-a-03.jpg'],
  ['v-family-happy','video','動画','ずっと幸せな家族でいるには？','assets/thumbs/v-color-a-04.jpg'],
  ['v-sad-end','video','動画','つらいことや悲しいこと いつかなくなる？','assets/thumbs/v-color-a-05.jpg'],
  ['v-kingdomhall','video','動画','王国会館においでください','assets/thumbs/v-color-a-06.jpg'],
  ['v-witnesses','video','動画','エホバの証人 どんな人たちですか','assets/thumbs/v-color-a-07.jpg'],
  ['v-bible-study','video','動画','聖書レッスンを楽しんでください！','assets/thumbs/v-color-b-01.jpg'],
  ['v-lost-loved','video','動画','大切な人を亡くしても','assets/thumbs/v-color-b-02.jpg'],
  ['v-death-end','video','動画','死んだらそれで終わりですか','assets/thumbs/v-color-b-03.jpg'],
  ['v-family-book-intro','video','動画','「あなたの家族も幸せになれます」の紹介','assets/thumbs/v-color-b-04.jpg'],
  ['v-good-news','video','動画','良い知らせを聞きたいと思いませんか','assets/thumbs/v-color-b-05.jpg'],
  ['v-2026-convention','video','動画','2026年 エホバの証人の「永遠の幸せ」大会にお越しください','assets/thumbs/v-color-b-06.jpg'],
  ['v-jesus-drama-456','video','動画','ドラマ予告編 イエスが伝えた良い知らせ 第4話･第5話･第6話','assets/thumbs/v-color-c-01.jpg'],
  ['v-jesus-drama-23','video','動画','ドラマ予告編 イエスが伝えた良い知らせ 第2話･第3話','assets/thumbs/v-color-c-02.jpg'],
  ['v-jesus-death','video','動画','イエスの死を思い起こしましょう','assets/thumbs/v-color-c-03.jpg'],
  ['v-why-study','video','動画','聖書を学ぶとよいのはどうして？','assets/thumbs/v-color-c-04.jpg'],
  ['v-why-study-full','video','動画','聖書を学ぶとよいのはどうして？（フルバージョン）','assets/thumbs/v-color-c-05.jpg'],
  ['v-lesson-guide','video','動画','聖書レッスンのご案内','assets/thumbs/v-color-c-06.jpg'],
  ['w-friends','whiteboard','ホワイトボード','本当の友達とは？','assets/thumbs/v-white-a-01.jpg'],
  ['w-bully','whiteboard','ホワイトボード','いじめっ子を殴らずに撃退する','assets/thumbs/v-white-a-02.jpg'],
  ['w-parent','whiteboard','ホワイトボード','親と上手に話すには？','assets/thumbs/v-white-a-03.jpg'],
  ['w-device','whiteboard','ホワイトボード','電子機器 使っている？使われている？','assets/thumbs/v-white-a-04.jpg'],
  ['w-freedom','whiteboard','ホワイトボード','もっと自由がほしいなら','assets/thumbs/v-white-a-05.jpg'],
  ['w-rumor','whiteboard','ホワイトボード','うわさ話をやめるには？','assets/thumbs/v-white-a-06.jpg'],
  ['w-love','whiteboard','ホワイトボード','愛？それとも恋？','assets/thumbs/v-white-a-07.jpg'],
  ['w-pressure','whiteboard','ホワイトボード','仲間の圧力に負けないために','assets/thumbs/v-white-a-08.jpg'],
  ['w-sns','whiteboard','ホワイトボード','SNSをスマートに','assets/thumbs/v-white-a-09.jpg'],
  ['w-fake-news','whiteboard','ホワイトボード','間違った情報に気を付けて！','assets/thumbs/v-white-b-01.jpg'],
  ['w-money','whiteboard','ホワイトボード','お金を上手に使おう','assets/thumbs/v-white-b-02.jpg'],
  ['w-smoke','whiteboard','ホワイトボード','煙と一緒に消えないで！','assets/thumbs/v-white-b-03.jpg'],
  ['w-game','whiteboard','ホワイトボード','ゲーム あなたは本当の勇者？','assets/thumbs/v-white-b-04.jpg'],
  ['w-tears','whiteboard','ホワイトボード','涙から、笑顔へ','assets/thumbs/v-white-b-05.jpg'],
  ['w-sport','whiteboard','ホワイトボード','スポーツを楽しむには','assets/thumbs/v-white-b-06.jpg'],
  ['w-alcohol','whiteboard','ホワイトボード','お酒を勧められたら？','assets/thumbs/v-white-b-07.jpg'],
  ['w-lonely','whiteboard','ホワイトボード','寂しいと感じる時どうしたらいい？','assets/thumbs/v-white-c-01.jpg'],
  ['w-older','whiteboard','ホワイトボード','年配の人たちは最高の友達！','assets/thumbs/v-white-c-02.jpg'],
  ['w-bible-useful','whiteboard','ホワイトボード','聖書はためになる本だと思う？','assets/thumbs/v-white-c-03.jpg'],
  ['w-school','whiteboard','ホワイトボード','なんで学校に行かなきゃいけないの？','assets/thumbs/v-white-c-04.jpg'],
  ['w-honest','whiteboard','ホワイトボード','なぜ正直って大切？','assets/thumbs/v-white-c-05.jpg'],
  ['w-clean','whiteboard','ホワイトボード','清潔感あるスマートな人に','assets/thumbs/v-white-c-06.jpg'],
  ['w-prejudice','whiteboard','ホワイトボード','偏見 もしかして私も？','assets/thumbs/v-white-c-07.jpg']
];

function blankState(){return {version:1,records:[],people:[],baseline:{start:serviceYearStart(),normalMinutes:parseTime('424:20'),extraMinutes:parseTime('71:00'),note:'移行累計'},favorites:Object.fromEntries(MEDIA.slice(0,20).map(x=>[x[0],true])),recent:[],firebaseConfig:FIREBASE_CONFIG,updatedAt:Date.now()};}
function normalizeRecord(r){ if(!r) return null; const activity=r.activityType||r.activity||'戸別'; const extra=/大会|メンテ|付加|災害/.test(activity); return {id:r.id||uid(),date:r.date||today(),activityType:activity,normalMinutes:parseTime(r.normalMinutes ?? (extra?0:r.minutes)),extraMinutes:parseTime(r.extraMinutes ?? (extra?r.minutes:0)),personId:r.personId||'',personName:r.personName||r.contactName||r.name||'',gender:r.gender||'',ageGroup:r.ageGroup||'',territory:r.territory||'',block:r.block||'',building:r.building||'',address:r.address||'',lat:r.lat??r.latitude??null,lng:r.lng??r.longitude??null,rvStatus:r.rvStatus||'関心あり',nextDate:r.nextDate||'',topics:Array.isArray(r.topics)?r.topics:[],lessonStatus:r.lessonStatus||'なし',lessonMaterial:r.lessonMaterial||'',lessonNo:r.lessonNo||'',media:Array.isArray(r.media)?r.media:[...(r.publications||[]),...(r.videos||[])].map(x=>typeof x==='string'?x:x.id).filter(Boolean),memo:r.memo||'',createdAt:r.createdAt||Date.now(),updatedAt:r.updatedAt||Date.now()}; }
function normalizePerson(p){ if(!p) return null; return {id:p.id||uid(),name:p.name||p.personName||p.contactName||'名前未入力',gender:p.gender||'',ageGroup:p.ageGroup||'',territory:p.territory||'',block:p.block||'',building:p.building||'',address:p.address||'',lat:p.lat??p.latitude??null,lng:p.lng??p.longitude??null,rvStatus:p.rvStatus||'関心あり',nextDate:p.nextDate||'',topics:Array.isArray(p.topics)?p.topics:[],lessonStatus:p.lessonStatus||'なし',lessonMaterial:p.lessonMaterial||'',lessonNo:p.lessonNo||'',memo:p.memo||'',createdAt:p.createdAt||Date.now(),updatedAt:p.updatedAt||Date.now()}; }
function normalizeState(s){s=s||{}; const n=blankState(); n.records=(s.records||[]).map(normalizeRecord).filter(Boolean); n.people=(s.people||[]).map(normalizePerson).filter(Boolean); n.baseline={start:(s.baseline&&s.baseline.start)||serviceYearStart(),normalMinutes:parseTime(s.baseline?.normalMinutes??s.baseline?.serviceMinutes??s.baseline?.minutes??n.baseline.normalMinutes),extraMinutes:parseTime(s.baseline?.extraMinutes??n.baseline.extraMinutes),note:s.baseline?.note||n.baseline.note}; n.favorites=s.favorites||n.favorites; n.recent=Array.isArray(s.recent)?s.recent:[]; n.firebaseConfig=s.firebaseConfig||FIREBASE_CONFIG; ensurePeople(n); return n;}
function personKey(p){return [p.name||'',p.address||'',p.building||''].join('|').trim();}
function ensurePeople(s){const byKey=new Map(s.people.map(p=>[personKey(p),p])); for(const r of s.records){if(!r.personName&&!r.address) continue; let p=r.personId?s.people.find(x=>x.id===r.personId):null; if(!p){let key=personKey({name:r.personName,address:r.address,building:r.building}); p=byKey.get(key);}
 if(!p){p=normalizePerson({...r,name:r.personName||'名前未入力'}); s.people.push(p); byKey.set(personKey(p),p);} r.personId=p.id;}}
function loadState(){let raw=localStorage.getItem(STORE_KEY); if(raw){try{return normalizeState(JSON.parse(raw));}catch(e){console.warn(e)}} const fresh=blankState(); return fresh;}
let state=loadState(), editingId=null, currentNormal=0, currentExtra=0, currentLat=null, currentLng=null, selectedMedia=[], map=null, markers=[], auth=null, db=null, user=null;
function saveLocal(){state.updatedAt=Date.now(); localStorage.setItem(STORE_KEY,JSON.stringify(state));}
function sums(){const m=today().slice(0,7), st=state.baseline.start||serviceYearStart(); let mn=0,me=0,yn=state.baseline.normalMinutes||0,ye=state.baseline.extraMinutes||0; for(const r of state.records){if((r.date||'').slice(0,7)===m){mn+=r.normalMinutes;me+=r.extraMinutes} if((r.date||'')>=st){yn+=r.normalMinutes;ye+=r.extraMinutes}} return {mn,me,yn,ye};}
function renderSummary(){const x=sums(); $('#monthNormal').textContent=fmt(x.mn); $('#monthExtra').textContent=fmt(x.me); $('#monthTotal').textContent=fmt(x.mn+x.me); $('#yearNormal').textContent=fmt(x.yn); $('#yearExtra').textContent=fmt(x.ye); $('#yearTotal').textContent=fmt(x.yn+x.ye); $('#personCount').textContent=state.people.length; $('#lessonCount').textContent=state.people.filter(p=>p.lessonStatus==='レッスン中').length;}
function setTab(t){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===t)); $$('.panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+t)); if(t==='map') setTimeout(renderMap,100);}
function setTimes(n,e){currentNormal=Math.max(0,n||0);currentExtra=Math.max(0,e||0); $('#normalDisplay').textContent=fmt(currentNormal); $('#extraDisplay').textContent=fmt(currentExtra);}
function getTopics(){return $$('.topic:checked').map(x=>x.value)}
function setTopics(vals=[]){$$('.topic').forEach(x=>x.checked=vals.includes(x.value))}
function getRecordFromForm(){return normalizeRecord({id:editingId||uid(),date:$('#date').value||today(),activityType:$('#activityType').value,normalMinutes:currentNormal,extraMinutes:currentExtra,personId:$('#personSelect').value,personName:$('#personName').value.trim(),gender:$('#gender').value,ageGroup:$('#ageGroup').value,territory:$('#territory').value.trim(),block:$('#block').value,building:$('#building').value.trim(),address:$('#address').value.trim(),lat:currentLat,lng:currentLng,rvStatus:$('#rvStatus').value,nextDate:$('#nextDate').value,topics:getTopics(),lessonStatus:$('#lessonStatus').value,lessonMaterial:$('#lessonMaterial').value.trim(),lessonNo:$('#lessonNo').value.trim(),media:selectedMedia,memo:$('#memo').value.trim(),createdAt:editingId?(state.records.find(r=>r.id===editingId)?.createdAt||Date.now()):Date.now(),updatedAt:Date.now()});}
function upsertPerson(r){if(!$('#saveToPerson').checked) return r.personId; if(!r.personName&&!r.address) return r.personId; let p=r.personId?state.people.find(x=>x.id===r.personId):null; if(!p){const key=personKey({name:r.personName,address:r.address,building:r.building}); p=state.people.find(x=>personKey(x)===key);} if(!p){p=normalizePerson({name:r.personName||'名前未入力'}); state.people.push(p);} Object.assign(p,{name:r.personName||p.name,gender:r.gender||p.gender,ageGroup:r.ageGroup||p.ageGroup,territory:r.territory||p.territory,block:r.block||p.block,building:r.building||p.building,address:r.address||p.address,lat:r.lat??p.lat,lng:r.lng??p.lng,rvStatus:r.rvStatus,nextDate:r.nextDate,topics:r.topics,lessonStatus:r.lessonStatus,lessonMaterial:r.lessonMaterial,lessonNo:r.lessonNo,memo:r.memo||p.memo,updatedAt:Date.now()}); return p.id;}
function clearForm(){editingId=null; $('#date').value=today(); $('#activityType').value='戸別'; setTimes(0,0); selectedMedia=[]; renderSelectedMedia(); ['personName','gender','ageGroup','territory','block','building','address','nextDate','lessonMaterial','lessonNo','memo'].forEach(id=>$('#'+id).value=''); $('#personSelect').value=''; $('#rvStatus').value='関心あり'; $('#lessonStatus').value='なし'; setTopics([]); currentLat=null; currentLng=null; $('#saveBtn').textContent='記録を保存';}
function saveRecord(){const r=getRecordFromForm(); r.personId=upsertPerson(r); const i=state.records.findIndex(x=>x.id===r.id); if(i>=0) state.records[i]=r; else state.records.push(r); selectedMedia.forEach(id=>{state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,30)}); saveLocal(); clearForm(); renderAll(); alert('保存しました');}
function fillForm(r){editingId=r.id; $('#date').value=r.date; $('#activityType').value=r.activityType; setTimes(r.normalMinutes,r.extraMinutes); $('#personSelect').value=r.personId||''; ['personName','gender','ageGroup','territory','block','building','address','rvStatus','nextDate','lessonStatus','lessonMaterial','lessonNo','memo'].forEach(id=>{$('#'+id).value=r[id]||''}); currentLat=r.lat; currentLng=r.lng; selectedMedia=[...(r.media||[])]; setTopics(r.topics||[]); renderSelectedMedia(); $('#saveBtn').textContent='更新する'; setTab('record'); scrollTo({top:0,behavior:'smooth'});}
function applyPerson(id){const p=state.people.find(x=>x.id===id); if(!p) return; ['name','gender','ageGroup','territory','block','building','address','rvStatus','nextDate','lessonStatus','lessonMaterial','lessonNo','memo'].forEach(k=>{const id2=k==='name'?'personName':k; if($('#'+id2)) $('#'+id2).value=p[k]||''}); currentLat=p.lat; currentLng=p.lng; setTopics(p.topics||[]);}
function mediaById(id){return MEDIA.find(x=>x[0]===id)}
function cardHTML(m, selectMode=false){const on=selectedMedia.includes(m[0]); return `<button class="media-card ${on?'selected':''}" data-media-id="${m[0]}" type="button"><img src="${m[4]}" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')" alt="" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')"><span class="media-kind">${esc(m[2])}</span><b>${esc(m[3])}</b>${selectMode?'<em>'+(on?'選択中':'選択')+'</em>':''}</button>`;}
function renderSelectedMedia(){const box=$('#selectedMedia'); if(!box) return; box.innerHTML=selectedMedia.length?selectedMedia.map(id=>{const m=mediaById(id); return m?`<span class="pill-thumb"><img src="${m[4]}" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')">${esc(m[3])}<button type="button" data-remove-media="${id}">×</button></span>`:''}).join(''):'<span class="muted">未選択</span>';}
function mediaFilterList(){let q=($('#mediaSearch')?.value||'').toLowerCase(); let kind=$('#mediaKind')?.value||'all'; return MEDIA.filter(m=>(kind==='all'||m[1]===kind||m[2]===kind)&&(m[3]+m[2]).toLowerCase().includes(q));}
function renderLibrary(){if(!$('#libraryGrid')) return; $('#libraryGrid').innerHTML=mediaFilterList().map(m=>cardHTML(m,true)).join('');}
function renderPeople(){const q=($('#peopleSearch')?.value||'').toLowerCase(); const rows=state.people.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).sort((a,b)=>(a.nextDate||'9999').localeCompare(b.nextDate||'9999')); $('#peopleList').innerHTML=rows.length?rows.map(p=>{const recs=state.records.filter(r=>r.personId===p.id); const media=[...new Set(recs.flatMap(r=>r.media||[]))].slice(0,6); return `<div class="person-row"><div><h3>${esc(p.name)} ${p.lessonStatus==='レッスン中'?'<span class="badge">レッスン中</span>':''}</h3><p>${esc([p.gender,p.ageGroup,p.territory,p.block].filter(Boolean).join(' / '))}</p><p>${esc(p.address||'')} ${esc(p.building||'')}</p><p>次回: ${esc(p.nextDate||'未定')} / 履歴 ${recs.length}件</p><div class="mini-media">${media.map(id=>{const m=mediaById(id);return m?`<img title="${esc(m[3])}" src="${m[4]}" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')">`:''}).join('')}</div></div><div class="row-actions"><button data-person-record="${p.id}">記録</button><button data-person-detail="${p.id}">詳細</button><button data-person-edit="${p.id}">編集</button></div></div>`}).join(''):'<p class="muted">人物はまだありません。記録保存時に自動登録できます。</p>';}
function showPersonDetail(id){const p=state.people.find(x=>x.id===id); if(!p) return; const recs=state.records.filter(r=>r.personId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||'')); $('#detailContent').innerHTML=`<h3>${esc(p.name)}</h3><p>${esc([p.gender,p.ageGroup,p.territory,p.block].filter(Boolean).join(' / '))}</p><p>${esc(p.address||'')} ${esc(p.building||'')}</p><p>次回: ${esc(p.nextDate||'未定')} / ${esc(p.lessonStatus||'')}</p><hr>${recs.map(r=>`<div class="detail-rec"><b>${esc(r.date)} ${esc(r.activityType)} 通常${fmt(r.normalMinutes)} 付加${fmt(r.extraMinutes)}</b><p>${esc(r.memo||'')}</p><div class="mini-media">${(r.media||[]).map(id=>{const m=mediaById(id); return m?`<img title="${esc(m[3])}" src="${m[4]}" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')">`:''}).join('')}</div></div>`).join('')||'<p>履歴なし</p>'}`; setTab('detail');}
function renderHistory(){const q=($('#historySearch')?.value||'').toLowerCase(); const rows=state.records.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||0)-(a.createdAt||0)); $('#historyList').innerHTML=rows.length?rows.map(r=>`<div class="history-row"><div><b>${esc(r.date)} ${esc(r.activityType)} 通常${fmt(r.normalMinutes)} 付加${fmt(r.extraMinutes)}</b><p>${esc(r.personName||'')} ${esc(r.gender||'')} ${esc(r.ageGroup||'')}</p><p>${esc([r.territory,r.block,r.address,r.building].filter(Boolean).join(' / '))}</p><div class="mini-media">${(r.media||[]).map(id=>{const m=mediaById(id);return m?`<img title="${esc(m[3])}" src="${m[4]}" onerror="this.onerror=null;this.src=this.src.replace('assets/thumbs/','資産/親指/')">`:''}).join('')}</div></div><div class="row-actions"><button data-rec-edit="${r.id}">編集</button><button class="danger" data-rec-delete="${r.id}">削除</button></div></div>`).join(''):'<p class="muted">履歴はありません。</p>';}
function renderPersonSelect(){const sel=$('#personSelect'); const cur=sel.value; sel.innerHTML='<option value="">新規または未選択</option>'+state.people.map(p=>`<option value="${p.id}">${esc(p.name)}${p.territory?' / '+esc(p.territory):''}</option>`).join(''); sel.value=cur;}
function renderStats(){const by={}; for(const r of state.records){const m=(r.date||'').slice(0,7)||'未日付'; by[m]??={n:0,e:0,c:0}; by[m].n+=r.normalMinutes; by[m].e+=r.extraMinutes; by[m].c++;} $('#statsBox').innerHTML='<table><tr><th>月</th><th>通常</th><th>付加</th><th>合計</th><th>件数</th></tr>'+Object.entries(by).sort().reverse().map(([m,x])=>`<tr><td>${m}</td><td>${fmt(x.n)}</td><td>${fmt(x.e)}</td><td>${fmt(x.n+x.e)}</td><td>${x.c}</td></tr>`).join('')+'</table>';}
function renderBaseline(){ $('#baseStart').value=state.baseline.start||serviceYearStart(); $('#baseNormal').value=fmt(state.baseline.normalMinutes||0); $('#baseExtra').value=fmt(state.baseline.extraMinutes||0); $('#baseNote').value=state.baseline.note||'';}
function renderAll(){renderSummary();renderPersonSelect();renderSelectedMedia();renderLibrary();renderPeople();renderHistory();renderStats();renderBaseline(); if($('#tab-map').classList.contains('active')) renderMap();}
function saveBaseline(){state.baseline={start:$('#baseStart').value||serviceYearStart(),normalMinutes:parseTime($('#baseNormal').value),extraMinutes:parseTime($('#baseExtra').value),note:$('#baseNote').value}; saveLocal(); renderAll(); alert('保存しました');}
async function geocodeAddress(){const addr=$('#address').value.trim(); if(!addr){alert('住所を入力してください');return;} try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(addr)); const arr=await res.json(); if(!arr.length){alert('見つかりませんでした');return;} currentLat=+arr[0].lat; currentLng=+arr[0].lon; alert('ピン位置を取得しました');}catch(e){alert('住所検索に失敗しました');}}
function useLocation(){if(!navigator.geolocation){alert('位置情報が使えません');return;} navigator.geolocation.getCurrentPosition(p=>{currentLat=p.coords.latitude;currentLng=p.coords.longitude;alert('現在地を取得しました');},e=>alert(e.message),{enableHighAccuracy:true,timeout:10000});}
function openMap(){const addr=$('#address').value.trim(); const q=currentLat&&currentLng?`${currentLat},${currentLng}`:addr; if(!q){alert('住所か位置が必要です');return;} open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank');}
function renderMap(){if(!window.L)return; if(!map){map=L.map('map').setView([34.7108,137.7261],12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);} markers.forEach(m=>m.remove()); markers=[]; const pts=state.people.filter(p=>p.lat&&p.lng); pts.forEach(p=>markers.push(L.marker([p.lat,p.lng]).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br>${esc(p.address||'')}<br>次回:${esc(p.nextDate||'未定')}`))); if(pts.length) map.fitBounds(pts.map(p=>[p.lat,p.lng]),{padding:[30,30]}); setTimeout(()=>map.invalidateSize(),100);}
function exportJson(){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})); a.download='ministry-hub-backup.json'; a.click();}
async function importJson(file){const incoming=normalizeState(JSON.parse(await file.text())); if(!confirm('バックアップを現在のデータと統合しますか？'))return; const rec=new Map(state.records.map(r=>[r.id,r])); incoming.records.forEach(r=>rec.set(r.id,r)); const ppl=new Map(state.people.map(p=>[p.id,p])); incoming.people.forEach(p=>ppl.set(p.id,p)); state=normalizeState({...state,records:[...rec.values()],people:[...ppl.values()],baseline:incoming.baseline||state.baseline,favorites:{...state.favorites,...incoming.favorites}}); saveLocal(); renderAll(); alert('復元しました');}
function initFirebase(){try{const cfg=state.firebaseConfig||FIREBASE_CONFIG; $('#firebaseConfig').value=JSON.stringify(cfg,null,2); if(!firebase.apps.length) firebase.initializeApp(cfg); auth=firebase.auth(); db=firebase.firestore(); auth.onAuthStateChanged(u=>{user=u; $('#loginBtn').hidden=!!u; $('#logoutBtn').hidden=!u; $('#syncStatus').textContent=u?'同期準備OK: '+(u.email||''): '未ログイン';});}catch(e){$('#syncStatus').textContent='Firebase設定エラー: '+e.message;}}
async function cloudPush(){if(!user||!db){alert('先にログインしてください');return;} await db.collection('users').doc(user.uid).collection('apps').doc('ministryHubFinalSafe').set({state,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}); alert('クラウドへ保存しました');}
async function cloudPull(){if(!user||!db){alert('先にログインしてください');return;} const snap=await db.collection('users').doc(user.uid).collection('apps').doc('ministryHubFinalSafe').get(); if(!snap.exists){alert('クラウドにデータがありません');return;} if(!confirm('クラウドから読み込み、端末データと統合しますか？'))return; const incoming=normalizeState(snap.data().state); const rec=new Map(state.records.map(r=>[r.id,r])); incoming.records.forEach(r=>rec.set(r.id,r)); const ppl=new Map(state.people.map(p=>[p.id,p])); incoming.people.forEach(p=>ppl.set(p.id,p)); state=normalizeState({...state,records:[...rec.values()],people:[...ppl.values()],baseline:incoming.baseline||state.baseline,favorites:{...state.favorites,...incoming.favorites}}); saveLocal(); renderAll(); alert('読み込みました');}
function bind(){ $('#tabs').addEventListener('click',e=>{if(e.target.dataset.tab)setTab(e.target.dataset.tab)}); document.body.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; if(b.dataset.delta){const target=b.dataset.target, delta=parseInt(b.dataset.delta,10)||0; if(target==='normal') setTimes(currentNormal+delta,currentExtra); if(target==='extra') setTimes(currentNormal,currentExtra+delta);} if(b.dataset.mediaId){const id=b.dataset.mediaId; selectedMedia=selectedMedia.includes(id)?selectedMedia.filter(x=>x!==id):[...selectedMedia,id]; renderSelectedMedia(); renderLibrary();} if(b.dataset.removeMedia){selectedMedia=selectedMedia.filter(x=>x!==b.dataset.removeMedia); renderSelectedMedia(); renderLibrary();} if(b.dataset.recEdit) fillForm(state.records.find(r=>r.id===b.dataset.recEdit)); if(b.dataset.recDelete&&confirm('削除しますか？')){state.records=state.records.filter(r=>r.id!==b.dataset.recDelete);saveLocal();renderAll();} if(b.dataset.personRecord){$('#personSelect').value=b.dataset.personRecord; applyPerson(b.dataset.personRecord); setTab('record');} if(b.dataset.personEdit){$('#personSelect').value=b.dataset.personEdit; applyPerson(b.dataset.personEdit); setTab('record');} if(b.dataset.personDetail) showPersonDetail(b.dataset.personDetail);}); $('#personSelect').onchange=e=>applyPerson(e.target.value); $('#saveBtn').onclick=saveRecord; $('#clearBtn').onclick=clearForm; $('#geoBtn').onclick=geocodeAddress; $('#locBtn').onclick=useLocation; $('#mapBtn').onclick=openMap; $('#mediaSearch').oninput=renderLibrary; $('#mediaKind').onchange=renderLibrary; $('#peopleSearch').oninput=renderPeople; $('#historySearch').oninput=renderHistory; $('#saveBaseBtn').onclick=saveBaseline; $('#exportBtn').onclick=exportJson; $('#importBtn').onclick=()=>$('#importFile').click(); $('#importFile').onchange=e=>{const f=e.target.files[0]; if(f) importJson(f); e.target.value='';}; $('#loginBtn').onclick=()=>auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(e=>alert(e.message)); $('#logoutBtn').onclick=()=>auth.signOut(); $('#cloudPushBtn').onclick=cloudPush; $('#cloudPullBtn').onclick=cloudPull; $('#saveFirebaseBtn').onclick=()=>{try{state.firebaseConfig=JSON.parse($('#firebaseConfig').value);saveLocal();alert('保存しました。再読み込みします');location.reload();}catch(e){alert('JSONを確認してください');}};}
function init(){clearForm(); bind(); renderAll(); initFirebase();}
document.addEventListener('DOMContentLoaded',init);
